wandb_version: 1

__is_set:
  desc: null
  value:
    wallet.name: true
    wallet.hotkey: true
    subtensor.network: true
    device: true
    use_wandb: true
name:
  desc: null
  value: null
netuid:
  desc: null
  value: 212
bucket:
  desc: null
  value: decis
batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0001
optimizer_beta1:
  desc: null
  value: 0.9
optimizer_beta2:
  desc: null
  value: 0.95
optimizer_weight_decay:
  desc: null
  value: 0.1
num_pages:
  desc: null
  value: 5
device:
  desc: null
  value: cuda:1
use_wandb:
  desc: null
  value: true
no_prompt:
  desc: null
  value: false
wallet:
  desc: null
  value:
    __is_set: {}
    name: Alice
    hotkey: Bob
    path: ~/.bittensor/wallets/
subtensor:
  desc: null
  value:
    __is_set: {}
    network: test
    chain_endpoint: wss://entrypoint-finney.opentensor.ai:443
    _mock: false
config:
  desc: null
  value: null
strict:
  desc: null
  value: false
no_version_checking:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725922685
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.7
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
